export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_ERROR = 'PRODUCT_DETAILS_ERROR';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING = 'CART_SAVE_SHIPPING'
export const CART_SAVE_PAYMENT = 'CART_SAVE_PAYMENT'

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_ERROR = 'USER_SIGNIN_ERROR'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR'

export const PRODUCT_SAVE_REQUEST = 'PRODUCT_SAVE_REQUEST'
export const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_SUCCESS'
export const PRODUCT_SAVE_ERROR = 'PRODUCT_SAVE_ERROR'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCES = 'PRODUCT_DELETE_SUCCES'
export const PRODUCT_DELETE_ERROR = 'PRODUCT_DELETE_ERROR'

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_ERROR = 'ORDER_CREATE_REQUEST'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_ERROR = 'ORDER_DETAILS_REQUEST'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_ERROR = 'ORDER_PAY_ERROR'

export const MY_ORDER_LIST_REQUEST = 'MY_ORDER_LIST_REQUEST'
export const MY_ORDER_LIST_SUCCESS = 'MY_ORDER_LIST_SUCCESS'
export const MY_ORDER_LIST_ERROR = 'MY_ORDER_LIST_ERROR'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_ERROR = 'ORDER_LIST_ERROR'

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST'
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS'
export const ORDER_DELETE_ERROR = 'ORDER_DELETE_ERROR'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR'

export const CATEGORY_LIST_REQUEST = 'CATEGORYº_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORYº_LIST_SUCCESS';
export const CATEGORY_LIST_ERROR = 'CATEGORYº_LIST_ERROR';

export const CATEGORY_DETAILS_REQUEST = 'CATEGORYº_DETAILS_REQUEST';
export const CATEGORY_DETAILS_SUCCESS = 'CATEGORYº_DETAILS_SUCCESS';
export const CATEGORY_DETAILS_ERROR = 'CATEGORYº_DETAILS_ERROR';

export const CATEGORY_SAVE_REQUEST = 'CATEGORYº_SAVE_REQUEST'
export const CATEGORY_SAVE_SUCCESS = 'CATEGORYº_SAVE_SUCCESS'
export const CATEGORY_SAVE_ERROR = 'CATEGORYº_SAVE_ERROR'

export const CATEGORY_DELETE_REQUEST = 'CATEGORYº_DELETE_REQUEST'
export const CATEGORY_DELETE_SUCCES = 'CATEGORYº_DELETE_SUCCES'
export const CATEGORY_DELETE_ERROR = 'CATEGORYº_DELETE_ERROR'

export const USER_LOGOUT = 'USER_LOGOUT'